"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

maxfib = 4*10**6
fib1, fib2 = 1, 2
fibsum = 2
while fib2 < maxfib:
    fib1, fib2 = fib2, fib1 + fib2
    if fib2 % 2 == 0:
        fibsum += fib2
print(fibsum)
